title: Kotlin DDD Archetypes
email: 12781006+rdd13r@users.noreply.github.com
description: >-
  Customer 'Welcome Clerk' Aggregate Example
author: Vadim Kuhay
url: https://rdd13r.github.io
baseurl: /welcome-clerk

#logo: /assets/img/ddd.png
show_downloads: true
repository: rdd13r/welcome-clerk

remote_theme: jekyll/minima

plugins:
  - jekyll-remote-theme
  - jekyll-asciidoc

# Minima social links
twitter_username: VKuhay
github_username: rdd13r
linkedin_username: vadimkuhay
rss: rss

# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:
  - home.adoc
  - _pages/about.adoc
  - _pages/security.adoc
  - _pages/references.adoc
  - _pages/post-index.md

include:
  - _pages

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .git/
  - .github/
  - .gradle/
  - .idea/
  - .run/
  - _includes/
  - assets/
  - gradle/
  - src/
  - .en.text
  - .gitignore
  - .spellcheck.yml
  - ACKNOWLEDGMENTS.adoc
  - ATTRIBUTIONS.adoc
  - AUTHORS
  - build.gradle.kts
  - CHANGELOG.adoc
  - CODE_OF_CONDUCT.md
  - CODEOWNERS
  - _config.yml
  - CONTRIBUTING.adoc
  - CONTRIBUTORS
  - gradle.properties
  - gradlew
  - LICENSE
  - README
  - README.adoc
  - README.md
  - SECURITY.adoc
  - settings.gradle.kts
  - SUPPORT.adoc
  - docker-compose.yml
